const express = require('express')
const { body } = require('express-validator')
const router = express.Router()
const adminController = require('../controller/admin_controller')
const {verifyToken} = require('../utility/verifyToken')
const {verifyAdmin} = require('../utility/verify_role_admin')
router.post('/signup',body("email").isLength({min:8,max:50}).withMessage("typr valid email"),body('password').isLength({min:8,max:50}).withMessage('type valid password'),adminController.signUp)
router.post('/login',body("email").isNumeric().isLength({min:8,max:50}).withMessage("type valid email"),body('password').isLength({min:8,max:50}).withMessage('type valid password'),adminController.login)
router.post('/add',body("email").isLength({min:8,max:50}).withMessage("typr valid email"),body('password').isLength({min:8,max:50}).withMessage('type valid password'),verifyToken,verifyAdmin,adminController.addAdmin)
router.put('/edit',body('password').isLength({min:8,max:50}).withMessage('type valid password'),verifyToken,verifyAdmin,adminController.editAdminPassword)
router.get('/admins',verifyToken,verifyAdmin,adminController.getAdmins)
router.get('/statics',verifyToken,verifyAdmin,adminController.getStatics)
router.delete('/delete',verifyToken,verifyAdmin,adminController.deleteAdmin)
module.exports = router
