const express = require('express')
const { body } = require('express-validator')
const router = express.Router()
const authController = require('../controller/auth_user')
const {verifyToken} = require('../utility/verifyToken')
const { verifyAdmin } = require('../utility/verify_role_admin')
router.post('/signup',body('password').isLength({min:8,max:50}).withMessage('type valid password'),body('fullname').isString().isLength({min:6,max:30}).withMessage('type valid fullname'),body('phoneNumber').isNumeric().isLength({min:10,max:10}).withMessage('type valid phone number'),authController.signUp)
router.post('/login',body("phoneNumber").isNumeric().isLength({min:10,max:10}).withMessage("type valid phone number"),body('password').isLength({min:8,max:50}).withMessage('type valid password'),authController.login)
router.post('/logout',verifyToken,authController.logout)
router.put('/update-profile',verifyToken,authController.updateProfile)
router.put('/update-notification',verifyToken,authController.updateNotificationToken)
router.get('/user-info',verifyToken,authController.userInfo)
router.get('/inActive',verifyToken,verifyAdmin,authController.getInActiveUsers)
router.put('/active',verifyToken,verifyAdmin,authController.activeUser)
router.get('/active',verifyToken,verifyAdmin,authController.getActiveUsers)
router.put('/inActive',verifyToken,verifyAdmin,authController.inActiveUser)
router.put('/ban',verifyToken,verifyAdmin,authController.ban)
router.put('/disBan',verifyToken,verifyAdmin,authController.disBan)
router.put('/status',verifyToken,authController.changeUserStates)
module.exports = router
