const express = require('express')
const { body } = require('express-validator')
const router = express.Router()
const courseController = require('../controller/course_controller')
const {verifyToken} = require('../utility/verifyToken')
const { verifyAdmin } = require('../utility/verify_role_admin')
router.get('/course-info/:id',verifyToken,courseController.courseInfo)
router.get('/courses',verifyToken,courseController.courses)
router.delete('/delete',verifyToken,courseController.deleteCourse)
router.post('/add',verifyToken,verifyAdmin,courseController.addCourse)
router.put('/start',verifyToken,courseController.startCourse)
router.put('/finish',verifyToken,courseController.finishCourse)
router.get('/courses/admin',verifyToken,verifyAdmin,courseController.coursesAdmin)
router.get('/courses/user',verifyToken,verifyAdmin,courseController.courseOneUser)
module.exports = router