const express = require('express')
const { body } = require('express-validator')
const router = express.Router()
const ideaController = require('../controller/idea_controller')
const {verifyToken} = require('../utility/verifyToken')
const { verifyAdmin } = require('../utility/verify_role_admin')
// router.get('/course-info/:id',verifyToken,courseController.courseInfo)
// router.get('/courses',verifyToken,courseController.courses)
// router.delete('/delete',verifyToken,courseController.deleteCourse)
// router.post('/add',ideaController.addIdea)
// router.get('/ideas',ideaController.ideas)
// router.get('/statics',ideaController.ideaStatics)
// // router.get('/byType',maintenanceController.maintenanceByType)
// // router.post('/byType',maintenanceController.maintenanceType)
// // router.delete('/delete',maintenanceController.maintenanceDelete)
// // router.put('/start',verifyToken,courseController.startCourse)
// // router.put('/finish',verifyToken,courseController.finishCourse)
// // router.get('/payments/admin',verifyToken,verifyAdmin,paymentController.paymentsAdmin)
// // router.post('/payments/user',verifyToken,verifyAdmin,paymentController.paymentOneUser)
// module.exports = router