const express = require('express')
const { body } = require('express-validator')
const router = express.Router()
const paymentController = require('../controller/payment_controller')
const {verifyToken} = require('../utility/verifyToken')
const { verifyAdmin } = require('../utility/verify_role_admin')
// router.get('/course-info/:id',verifyToken,courseController.courseInfo)
router.get('/payments',verifyToken,paymentController.payments)
// router.delete('/delete',verifyToken,courseController.deleteCourse)
router.post('/add',verifyToken,verifyAdmin,paymentController.addPayment)
router.post('/add/daily',verifyToken,verifyAdmin,paymentController.addPaymentDaily)
router.post('/add/tax',verifyToken,verifyAdmin,paymentController.addTax)
// router.put('/start',verifyToken,courseController.startCourse)
// router.put('/finish',verifyToken,courseController.finishCourse)
router.get('/payments/admin',verifyToken,verifyAdmin,paymentController.paymentsAdmin)
router.post('/payments/user',verifyToken,verifyAdmin,paymentController.paymentOneUser)
module.exports = router
